uploads = []
outputs = []

[[generated]]
id = "_nV65cy8IdJDPk7_E2F2c"
uri = "file://artifacts/spudblocks/public/images/team-1.png"
type = "image"
title = "Male operator headshot"

[[generated]]
id = "-TXdxk9oWdKsOCE5oHHYr"
uri = "file://artifacts/spudblocks/public/images/team-2.png"
type = "image"
title = "Female operator headshot"

[[generated]]
id = "n46bB5vAukkVbFuyW7cdN"
uri = "file://artifacts/spudblocks/public/images/team-3.png"
type = "image"
title = "Male operator headshot"

[[generated]]
id = "b0sTBUaI7sENVUGrTfQnp"
uri = "file://artifacts/spudblocks/public/images/team-4.png"
type = "image"
title = "Female operator headshot"

[[generated]]
id = "N-eTSynFg5tXqprndbza5"
uri = "file://artifacts/spudblocks/public/images/team-5.png"
type = "image"
title = "Male operator headshot"

[[generated]]
id = "vWWsPZ0aRE9hJK8etRL5W"
uri = "file://artifacts/spudblocks/public/images/dashboard-mock.png"
type = "image"
title = "Operational dashboard mock"

[[generated]]
id = "gPHaHxjpGGofmRoF99CiC"
uri = "file://artifacts/spudblocks/public/images/case-1.png"
type = "image"
title = "Abstract case study cover"

[[generated]]
id = "8JWqlMPZ7K8AkBK8EgsGj"
uri = "file://artifacts/spudblocks/public/images/case-2.png"
type = "image"
title = "Abstract case study cover"

[[generated]]
id = "RTXI_HeEL86WvuIbC2Dxo"
uri = "file://artifacts/spudblocks/public/images/case-3.png"
type = "image"
title = "Abstract case study cover"
